spring.application.name=adirsa-proyectos

spring.datasource.url=jdbc:postgresql://localhost:5432/adirsa_gestion_proyectos
spring.datasource.username=postgres
spring.datasource.password=4583

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false